import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { supabase } from "../../components/SupabaseClient/SupabaseClient";
import MedalsHelper from "../../helper/MedalsHelper";

const MedalsInit = () => {
    // states
    const [title, setTitle] = useState("");
    const [loading, setLoading] = useState(true);
    const [scoreLoading, setScoreLoading] = useState(true);
    const [timeLoading, setTimeLoading] = useState(true);
    const [isMisc, setIsMisc] = useState(false);
    const [scoreMedals, setScoreMedals] = useState([]);
    const [timeMedals, setTimeMedals] = useState([]);

    // path variables
    const path = window.location.pathname;
    const abb = path.split("/")[2];
    const category = path.split("/")[3];

    // helper functions
    const { createUserMap, createMedalTable, addPositionToMedals } = MedalsHelper();

    // navigate used for redirecting
    const navigate = useNavigate();

    // in the event that the submission is empty, this query will be run to verify that the game
    // definied by abb is a valid game. if it is, it will just return an object with a single property:
    // the name of the game. otherwise, it will return an error object
    const checkAbb = async () => { 
        try {
            let { data: game, status, error } = await supabase
                .from("game")
                .select("abb, name")
                .eq("abb", abb)
                .single()

        // error handling
        if (error || status === 406) {
            throw error;
        }

        // if there are no errors, return the object generated by the query
        return game;

        } catch(error) {
            // if there is an error, return it
            if (error.code !== 'PGRST116') {
                console.log(error);
                alert(error);
            }
            return error;
        }
    }

    // function that will query the submissions page and generate a medal table leaderboard
    const medalTableQuery = async(type) => {
        try {
            // initialize variables
            const misc = category === "misc" ? true : false;
            if (category !== "main" && category !== "misc") {
                const error = { code: 1, message: "Error: invalid category." }
                throw error;
            }

            // query all submissions for abb that are also live in the {type} submission table
            let { data: submissions, status, error } = await supabase
                .from(`${type}_submission`)
                .select(`
                    profiles:user_id ( id, username, country, avatar_url ),
                    level (id, misc, mode (game (name))),
                    ${type},
                    live
                `)
                .eq("game_id", abb)
                .eq("live", true)
                .order(`${type}`, { ascending: false })

            // error handling
            if (error && status !== 406) {
                throw error;
            }

            // let's filter the list based on the status of the category
            submissions = submissions.filter(obj => obj.level.misc === misc);
            
            // if the submission query comes back empty, there are three possible explainations:
            // 1.) no submissions to game {type}
            // 2.) no live submissions to game {type}
            // 3.) the game is invalid
            // we need to handle case 3
            if (submissions.length === 0) {
                const obj = await checkAbb();
                if (!("name" in obj)) {
                    throw obj.code === "PGRST116" ? { code: 1, message: "Error: Invalid game." } : obj;
                } else {
                    setTitle(obj.name);
                    setIsMisc(misc);
                    type === "score" ? setScoreLoading(false) : setTimeLoading(false);
                }
                // in any case, we want to end the function early, since there are no submissions to process
                return;
            }

            // first, update the title state
            setTitle(submissions[0].level.mode.game.name);

            //next, generate medal table with positions
            const userMap = createUserMap(submissions);
            const medalTable = createMedalTable(userMap, submissions, type);
            addPositionToMedals(medalTable);

            // finally, update react states
            setIsMisc(misc);
            type === "score" ? setScoreMedals(medalTable) : setTimeMedals(medalTable);
            type === "score" ? setScoreLoading(false) : setTimeLoading(false);
            
            console.log(medalTable);
            console.log(submissions);

        } catch(error) {
            if (error.code === 1) {
                console.log(error.message);
            } else {
                console.log(error);
            }
            navigate("/");
        }
    }

    // function that simply returns the link back to the game's page
    const getLinkBack = () => {
        return `/games/${abb}`;
    }

    // function that allows user to navigate to the game's totalizer page
    const getLinkToTotals = () => {
        return `/games/${abb}/${category}/totalizer`;
    }

    return { title,
             loading,
             scoreLoading,
             timeLoading,
             isMisc, 
             scoreMedals,
             timeMedals,
             setLoading,
             medalTableQuery,
             getLinkBack, 
             getLinkToTotals 
    };
}

export default MedalsInit;