/* ===== IMPORTS ===== */
import { FunctionsHttpError } from "@supabase/supabase-js";
import { supabase } from "../SupabaseClient";

const FunctionsRead = () => {
  /* ===== FUNCTIONS ===== */

  // FUNCTION 1: invokeLeaderboards - function that invokes a single route of the leaderboards edge function
  // PRECONDITIONS (2 parameters):
  // 1.) route: a string representing the name of the route to invoke
  // 2.) body: an object containing the parameters of the route
  // POSTCONDITIONS (2 possible outcomes):
  // if the invocation is successful, the payload generated by the route is simply returned
  // otherwise, this function throws an error, which should be handled by the caller function
  const invokeLeaderboards = async (route, body) => {
    const { data, error } = await supabase.functions.invoke(
      `leaderboards/${route}`,
      { body },
    );

    // error handling. NOTE: unlike a postgrest error, a function error describes itself in the response body, which has to be
    // read asynchronously. a body which cannot be read leaves the original error untouched
    if (error) {
      if (error instanceof FunctionsHttpError) {
        const failure = await error.context.json().catch(() => null);
        if (failure?.message) {
          throw new Error(failure.message, { cause: error });
        }
      }
      throw error;
    }

    return data;
  };

  // FUNCTION 2: getRecords - function that invokes a route to generate the world records depending on the parameters
  // PRECONDITIONS (5 parameters):
  // 1.) abb: a string representing the unique identifier for a game
  // 2.) category: a string representing a valid category
  // 3.) type: a string, either "score" or "time"
  // 4.) live: a boolean value representing whether or not to filter by live submissions
  // 5.) version: an int OR undefined: an int if game has versions, otherwise undefined
  // POSTCONDITIONS (2 possible outcomes):
  // if the invocation is successful, the array of modes containing the record objects is simply returned
  // otherwise, this function throws an error, which should be handled by the caller function
  const getRecords = async (abb, category, type, live, version) => {
    return await invokeLeaderboards("records", {
      abb,
      category,
      score: type === "score",
      liveOnly: live,
      version: version ?? null,
    });
  };

  // FUNCTION 3: getTotals - function that invokes a route to generate a totalizer array depending on the parameters
  // PRECONDITIONS (5 parameters):
  // 1.) abb: a string representing the unique identifier for a game
  // 2.) category: a string representing a valid category
  // 3.) type: a string, either "score" or "time"
  // 4.) live: a boolean value representing whether or not to filter by live submissions
  // 5.) version: an int OR undefined: an int if game has versions, otherwise undefined
  // POSTCONDITIONS (2 possible outcomes):
  // if the invocation is successful, an array of totals objects, sorted by position field, is returned
  // otherwise, this function throws an error, which should be handled by the caller function
  const getTotals = async (abb, category, type, live, version) => {
    return await invokeLeaderboards("totals", {
      abb,
      category,
      score: type === "score",
      liveOnly: live,
      version: version ?? null,
    });
  };

  // FUNCTION 4: getUserRankings - function that invokes a route to generate a user ranking object depending on the parameters
  // PRECONDITIONS (6 parameters):
  // 1.) abb: a string representing the unique identifier for a game
  // 2.) category: a string representing a valid category
  // 3.) type: a string, either "score" or "time"
  // 4.) live: a boolean value representing whether or not to filter by live submissions
  // 5.) profileId: the id of the user whose rankings we want to grab
  // 6.) version: an int OR undefined: an int if game has versions, otherwise undefined
  // POSTCONDITIONS (2 possible outcomes):
  // if the invocation is successful, a user ranking object is returned
  // otherwise, this function throws an error, which should be handled by the caller function
  const getUserRankings = async (
    abb,
    category,
    type,
    live,
    profileId,
    version,
  ) => {
    return await invokeLeaderboards("user_rankings", {
      abb,
      category,
      score: type === "score",
      liveOnly: live,
      profileId,
      version: version ?? null,
    });
  };

  return {
    getRecords,
    getTotals,
    getUserRankings,
  };
};

/* ===== EXPORTS ===== */
export default FunctionsRead;
