/* ===== IMPORTS ===== */
import { MessageContext } from "../../utils/Contexts";
import { useContext, useState } from "react";

const GoalAddForm = () => {
    /* ===== CONTEXTS ===== */

    // add message function from message context
    const { addMessage } = useContext(MessageContext);

    /* ===== VARIABLES ===== */
    const valuesInit = {
        name: "",
        color: ""
    };
    const formInit = {
        values: valuesInit,
        error: { abb: undefined }
    };

    /* ===== STATES ===== */
    const [form, setForm] = useState(formInit);

    /* ===== FUNCTIONS ===== */

    // FUNCTION 1: handleChange - code that is executed when the user makes a change to the form
    // PRECONDITIONS (1 parameter):
    // 1.) e: an event object generated by the user's change to the form
    // POSTCONDITIONS (1 possible outcome):
    // the form is updated with the change the user makes
    const handleChange = e => {
        const { id, value } = e.target;
        setForm({ ...form, values: { ...form.values, [id]: value } });
    };
    
    // FUNCTION 2: handleSubmit - code that is executed when the user submits the form
    const handleSubmit = async () => {
        try {
            console.log("submitted!");
        } catch (error) {
            addMessage(error.message, "error", 5000);
        }
    };

    return { form, handleChange, handleSubmit };
};

/* ===== EXPORTS ===== */
export default GoalAddForm;